# Generated by Django 4.2.5 on 2023-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=90, null=True)),
                ('Description', models.CharField(blank=True, max_length=90, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='categoryimages')),
            ],
        ),
    ]
