# Generated by Django 4.2.5 on 2023-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=90, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=90, null=True)),
                ('Description', models.CharField(blank=True, max_length=90, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='productimages')),
            ],
        ),
    ]
