# Generated by Django 4.2.5 on 2023-11-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_productdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(blank=True, max_length=77, null=True)),
                ('City', models.CharField(blank=True, max_length=77, null=True)),
                ('Events', models.CharField(blank=True, max_length=77, null=True)),
                ('Palace', models.CharField(blank=True, max_length=77, null=True)),
                ('Contact', models.CharField(blank=True, max_length=77, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=77, null=True)),
            ],
        ),
    ]
