# Generated by Django 4.2.5 on 2023-11-24 14:49

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_bookingdb_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='Date',
            field=models.DateField(null=True, validators=[delivery.models.validate_future_date]),
        ),
    ]
