# Generated by Django 4.2.5 on 2023-11-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_bookingdb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='Name',
            field=models.CharField(blank=True, max_length=77, null=True),
        ),
    ]
