# Generated by Django 4.2.5 on 2023-10-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Dishname', models.CharField(blank=True, max_length=70, null=True)),
                ('Description', models.CharField(blank=True, max_length=70, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('TotalPrice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
