# Generated by Django 4.2.5 on 2023-10-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Username',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
