# Generated by Django 4.2.5 on 2023-11-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_cartdb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registerdb',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
